### PR TITLE
Update to v0.15.0

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Backlinking to purescript/purescript#4244

Updates project to compile on v0.15.0 PureScript.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Um.....
```
* Building project in /home/jordan/Programming/ps-libs/purescript/purescript-lists
[1 of 1] Compiling Data.List.Partial
[1/2 WildcardInferredType] src/Data/List/Partial.purs:21:1

  21  last :: forall a. Partial => List a -> a
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Wildcard type definition has the inferred type
  
    a0
  
  in binding group last
  
  where a0 is a rigid type variable
          bound at (line 0, column 0 - line 0, column 0)

[2/2 WildcardInferredType] src/Data/List/Partial.purs:28:1

  28  init :: forall a. Partial => List a -> List a
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Wildcard type definition has the inferred type
  
    List a0
  
  in binding group init
  
  where a0 is a rigid type variable
          bound at (line 0, column 0 - line 0, column 0)

           Src   Lib   All
Warnings   0     0     0  
Errors     2     0     2  
```

**Comment by JordanMartinez** [comment]
Should we ignore these compiler warnings for now?

**Comment by JordanMartinez** [comment]
Yeah, I just confirmed that it doesn't appear in `v0.14.5` but does in `v0.14.7`.

**Comment by JordanMartinez** [comment]
> Should we ignore these compiler warnings for now?

And to clarify, I mean ignore the warning in this repo for now, so that we can continue updating other libraries that depend on this one and agreeing to come back and fix this bug in the compiler before `v0.15.0` is released.

**Comment by thomashoneyman** [comment]
I think we should continue despite the warning, with the knowledge we need to sweep back around to it.

**Comment by JordanMartinez** [comment]
CI builds now.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
