### PR TITLE
Data.ZipList

### PR DESCRIPTION
**Pull request by paf31**
@garyb Could you please review? I thought this might be useful.

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

Should we stick it under `Data.List` with it being a newtype, rather than actually a different data structure?

**Comment by paf31** [comment]
I think it's best in its own module personally, but I don't feel too strongly. We do follow this "pattern" elsewhere though: `Par`, `Parallel`, `Additive` etc.

**Comment by garyb** [comment]
Sorry, yeah, I meant in the sense of `Data.List.ZipList`.

**Comment by paf31** [comment]
Oh right, yeah. Good idea.

**Pull request merged**
