### PR TITLE
Updates for 2.0

### LINKED ISSUE #75: Use NonEmpty for group, group' and groupBy?
Using purescript-nonempty, the signature of `group` could be changed from
``` purs
group :: forall a. Eq a => List a -> List (List a)
```
to
``` purs
group :: forall a. Eq a => List a -> List (NonEmpty List a)
```

I believe this is not just more descriptive, but also useful because it helps people to avoid `unsafePartial <<< Data.List.Partial.head` or similar constructions.

On the downside, it pulls in the purescript-nonempty dependency.

The same applies to `group'` and `groupBy`.

### PR DESCRIPTION
**Pull request by paf31**
Blocked by `generics`, and we should probably merge some of the open PRs first too. 

Resolves #75

### CODE REVIEW

**Comment by garyb** [comment]
Should we go back and make the `NonEmpty` changes to arrays too?

**Comment by paf31** [comment]
Yes, I think that's a good idea.

**Comment by garyb** [comment]
I think it's done at last :smile:

**Comment by paf31** [comment]
👍 Looks great!

**Pull request merged**
